backend:
  name: github
  repo: birdcall-online/kuma
  branch: main
  base_url: https://sveltia-cms-auth.birdcall-xyz.workers.dev

# backend:
#   name: test-repo

app_title: KUMA

logo:
  src: ../assets/logo.png
  show_in_header: true

i18n:
  structure: single_file
  locales: [ko, en]
  default_locale: ko

media_folder: /static/assets
public_folder: /assets

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          quality: 80
          width: 1200
          height: 1200
        svg:
          optimize: true

collections:
  - divider: true

  - name: kuma-about
    label: KUMA About
    i18n: true
    files:
      - name: kuma-about
        label: KUMA About
        file: content/kuma-about.md
        i18n: true
        fields:
          - label: 사진
            name: image
            widget: image
            i18n: duplicate
            required: true

          - label: 소개
            name: description
            widget: text
            i18n: true
            required: true

  - label: KUMA 운영위원회
    name: committee
    i18n: true

    files:
      - label: 운영위원회
        name: committee
        file: content/committee.md
        i18n: true

        fields:
          - label: 운영위원 목록
            name: items
            widget: list
            i18n: true

            fields:
              - label: 직책
                name: role
                widget: string
                i18n: true

              - label: 이름
                name: name
                widget: string
                i18n: true

              - label: 소속
                name: affiliation
                widget: string
                i18n: true

  - label: KUMA 대표 소장품
    name: collections
    i18n: true

    files:
      - label: 대표 소장품
        name: collections
        file: content/collections.md
        i18n: true

        fields:
          - label: 작품 목록
            name: items
            widget: list
            i18n: true
            summary: "{{fields.artist}} · {{fields.title}}"

            fields:
              - label: 사진
                name: image
                widget: image
                i18n: duplicate

              - label: 분류
                name: category
                widget: string
                i18n: true

              - label: 작가
                name: artist
                widget: string
                i18n: true

              - label: 작품명
                name: title
                widget: string
                i18n: true

              - label: 규격
                name: size
                widget: string
                i18n: true

              - label: 제작연도
                name: year
                widget: number
                i18n: duplicate

  - name: exhibitions
    label: KUMA Exhibitions
    folder: /content/exhibitions
    create: true
    media_folder: "{{media_folder}}/exhibitions/{{slug}}"
    public_folder: "{{public_folder}}/exhibitions/{{slug}}"
    i18n: true
    fields:
      - name: title
        label: 제목
        widget: string
        i18n: true
        required: true

      - name: type
        label: 유형
        widget: string
        i18n: true
        required: true

      - name: startDate
        label: 시작일
        widget: datetime
        type: date
        i18n: duplicate
        required: true

      - name: endDate
        label: 종료일
        widget: datetime
        type: date
        i18n: duplicate
        required: true

      - name: description
        label: 설명
        widget: markdown
        i18n: true
        required: true

      - name: images
        label: 사진
        widget: list
        i18n: duplicate
        required: false
        fields:
          - name: image
            label: 이미지
            widget: image

          - name: credit
            label: 크레딧
            widget: string
            required: false

  - label: KUMA Resources
    name: resources
    i18n: true

    files:
      - label: Resources
        name: resources
        file: content/resources.md
        i18n: true

        fields:
          - label: 자료 목록
            name: items
            widget: list
            i18n: true
            summary: "{{fields.type}} · {{fields.title}}"

            fields:
              - label: 형식
                name: type
                widget: string
                hint: PDF 등
                i18n: true

              - label: 제목
                name: title
                widget: string
                hint: 대관신청서 등
                i18n: true

              - label: 링크
                name: link
                widget: string
                hint: Google Drive 공유 링크 등
                i18n: duplicate

  - name: kuma-news
    label: KUMA News
    folder: /content/kuma-news
    required: false
    media_folder: "{{media_folder}}/kuma-news/{{slug}}"
    public_folder: "{{public_folder}}/kuma-news/{{slug}}"
    i18n: true

    fields:
      - name: type
        label: 형식
        widget: string
        hint: 보도자료 등
        i18n: true

      - name: title
        label: 제목
        widget: string
        i18n: true

      - name: link
        label: 링크
        widget: string
        hint: https:// 로 시작하는 URL
        i18n: duplicate

  - name: kuma-partners
    label: KUMA 협력사
    files:
      - label: 협력사
        name: partners
        file: content/kuma-partners.md
        fields:
          - label: 협력사 목록
            name: items
            widget: list
            summary: "{{fields.name}}"
            fields:
              - label: 이름
                name: name
                widget: string
                hint: 협력사 이름

              - label: 로고
                name: logo
                widget: image
                hint: 협력사 로고 이미지

  - divider: true

  - name: exkuma-sticker
    label: EX-KUMA Sticker
    i18n: true
    files:
      - name: exkuma-sticker
        label: EX-KUMA Sticker
        file: content/exkuma-sticker.md
        i18n: true
        fields:
          - label: 내용
            name: description
            widget: richtext
            i18n: true
            required: false
            hint: "내용을 비워두면 스티커가 표시되지 않습니다."

  - name: exkuma-about
    label: EX-KUMA About
    i18n: true
    files:
      - name: exkuma-about
        label: EX-KUMA About
        file: content/exkuma-about.md
        i18n: true
        fields:
          - label: 사진
            name: image
            widget: image
            i18n: duplicate
            required: true

          - label: 소개
            name: description
            widget: text
            i18n: true
            required: true
            hint: Unsettled 란?

  - name: exkuma-unsettled
    label: EX-KUMA Unsettled
    i18n: true
    files:
      - name: exkuma-unsettled
        label: EX-KUMA Unsettled
        file: content/exkuma-unsettled.md
        i18n: true
        fields:
          - label: 소개
            name: description
            widget: text
            i18n: true
            required: true

          - label: 포스터
            name: poster
            widget: image
            i18n: duplicate
            required: false

  - name: exkuma-workshops
    label: EX-KUMA Workshops
    folder: /content/workshops
    create: true
    media_folder: "{{media_folder}}/workshops/{{slug}}"
    public_folder: "{{public_folder}}/workshops/{{slug}}"
    i18n: true
    fields:
      - name: category
        label: 카테고리
        widget: list
        i18n: duplicate
        required: false
        field:
          label: 카테고리
          name: category
          widget: string

      - name: title
        label: 제목
        widget: string
        i18n: true
        required: true

      - name: description
        label: 설명
        widget: markdown
        i18n: true
        required: true

      - name: startDate
        label: 시작 날짜
        widget: datetime
        type: date
        i18n: duplicate
        required: true

      - name: endDate
        label: 종료 날짜
        widget: datetime
        type: date
        i18n: duplicate
        required: true

      - name: startTime
        label: 시작 시간
        widget: datetime
        type: time
        required: false

      - name: endTime
        label: 종료 시간
        widget: datetime
        type: time
        required: false

      - name: master
        label: 마스터
        widget: string
        i18n: true
        required: false

      - name: capacity
        label: 모집 인원
        widget: number
        value_type: int
        min: 0
        i18n: duplicate
        required: false

      - name: participants
        label: 참여 인원
        widget: number
        value_type: int
        min: 0
        i18n: duplicate
        required: false

      - name: applicationLink
        label: 신청 링크
        widget: string
        i18n: duplicate
        required: false

      - name: note
        label: 특이사항
        widget: string
        i18n: true
        required: false

      - name: images
        label: 사진
        widget: list
        i18n: duplicate
        required: false
        fields:
          - name: image
            label: 이미지
            widget: image

          - name: credit
            label: 크레딧
            widget: string
            required: false

  - name: exkuma-news
    label: EX-KUMA News
    folder: /content/exkuma-news
    required: false
    media_folder: "{{media_folder}}/exkuma-news/{{slug}}"
    public_folder: "{{public_folder}}/exkuma-news/{{slug}}"
    i18n: true
    fields:
      - name: type
        label: 형식
        widget: string
        i18n: true
        hint: 보도자료 등

      - name: title
        label: 제목
        widget: string
        i18n: true

      - name: link
        label: 링크
        widget: string
        hint: https:// 로 시작하는 URL
        i18n: duplicate

  - name: exkuma-partners
    label: EX-KUMA 협력사
    files:
      - label: 협력사
        name: partners
        file: content/exkuma-partners.md
        fields:
          - label: 협력사 목록
            name: items
            widget: list
            summary: "{{fields.name}}"
            fields:
              - label: 이름
                name: name
                widget: string
                hint: 협력사 이름

              - label: 로고
                name: logo
                widget: image
                hint: 협력사 로고 이미지
